export const environment = {
    production: true,
    endpoint: 'https://api.stage.sheba.xyz/',
    site_url: 'https://business.stage.sheba.xyz/',
    accounts_url: 'https://accounts.stage.sheba.xyz/',
    account_kit_url: 'https://accountkit.sheba.xyz/',
    bondhu_url: 'https://bondhu.sheba.xyz/',
    api_url: 'https://api.stage.sheba.xyz/',
    sheba_api_url: 'https://api.stage.sheba.xyz/',
    partner_url: 'https://partners.sheba.xyz/',
    customer_web_url: 'https://www.sheba.xyz/',
    topup_url: 'https://topup.sheba.xyz/',
    socket_url: 'https://www.sheba.xyz:3000/',
    google_analytics_id: 'UA-45794762-9',
    amplitude_id: 'fdc00bf648dec48d45e43f95302f407e',
    crisp_id: '1eeeecab-77c5-4472-8c25-7f230c0af262',
    sentry_key: 'https://1df852caabfe4fc2897f9cc304dd808a@sentry.io/4366199',
    help_url: 'https://help.sheba.xyz/',
    s3_url: 'https://cdn-business.s3.ap-south-1.amazonaws.com/release/',
    account_kit_app_id: '8329815A6D1AE6CC'
};
